export const USERS_COLLECTION = 'users';
export const GROUPS_FOR_USER_COLLECTION = 'groups-for-user';
export const GROUPS_SUBCOLLECTION = 'groups';
export const MEDICATIONS_FOR_GROUP_COLLECTION = 'medications-for-group';
export const MEDICATIONS_SUBCOLLECTION = 'medications';
export const MEDICATION_LOGS_COLLECTION = 'medication-logs';
export const LOGS_SUBCOLLECTION = 'logs';
export const GROUP_SHARING_FOR_USER = 'group-sharing-for-user';
export const SHARED_GROUPS_SUBCOLLECTION = 'shared-groups';
export const duration = 3000;

export { default as uniqueId } from './uniqueId';
export { default as useHandleChangeText } from './useHandleChangeText';
export { default as useSubmit } from './useSubmit';
export { default as HelpText } from './HelpText';
export { doesExist, isExact } from './validations';
export { default as Banner } from './Banner';
export { default as Button } from './Button';
export { default as Textbox } from './Textbox';
export { default as Fab } from './Fab';
export { default as SubText } from './SubText';
export { default as useValidation } from './useValidation';
export { default as useCollection } from './useCollection';
export { default as useDocument } from './useDocument';
